icebreakers = [
"Heard any good tips or advice lately?",
"Who was the last person you felt inspired by?",
"What simple thing still blows your mind?",
"Which question can you ask to find out the most about a person?",
"Have you been pleasantly surprised by anything recently?",
"Who has made a positive difference in your life recently?",
"What’s one country you would love to visit and why?",
"If you could be fluent in another language instantly, which would you choose, and why?",
"What’s something people don’t know about you?",
"What’s the most useful item you’ve purchased this year?",
"If you were setting off to Mars and could take only one luxury item with you, what would it be?",
"If you had to give a lecture on one thing, what would it be?",
"If you could become a supernatural creature at night, what would it be, and why?",
"If you could bring back a fashion trend, what would it be, and why?",
"What’s the most interesting thing in your fridge right now?",
"What was your favorite recent meal, and why?t ",
"If you could have an unlimited supply of one food or drink, what would it be?",
"What fictional world would you most like to live in?",
"You’re cooking for the whole cohort, what is your signature dish?",
"If you had a time machine, would you go back in time to meet your ancestors, or forward in time to meet your descendents?",
"If you could live with any fictional character, who would you choose?",
"What’s one skill that helps you successfully work remotely?",
"What’s the worst piece of advice you’ve ever been given? And why was it so bad?",
"If you could teleport anywhere in the world, where would you go right now?",
"Which fictional character would you want by your side during a zombie apocalypse?",
"What’s one thing many people hate, but you love?",
"What is your favorite smell and why?",
"What’s one productivity tool you couldn’t live without, and what makes it indispensable?",
"How do you get motivated for difficult tasks?",
"Look around and assess how satisfied you are with your physical workspace. What’s one thing you love about it?",
"Name a healthy food you enjoy and an unhealthy food that you find hard to resist.",
"What’s an adventurous thing you’ve done?",
"What’s the next item on your bucket list?",
"What's a TV show you recommend to everyone?",
"Where did you grow up and what was it like?",
"What are some strategies that you’ve found to be helpful in your recent work?",
"What’s something on your desk, a nearby wall, or out the window that cheers you up during the day?",
"Would you rather spend a three-week trip visiting multiple interesting destinations or one interesting destination?",
"What was your favorite breakfast as a kid?",
"What's something you rebelled against as a kid?",
"What were some of your favorite activities as a kid?",
"What’s a food, smell, or sound that you associate with where you grew up?",
"What’s a landmark, popular destination, or local hangout spot that you either frequented or avoided when you were growing up?",
"Would you rather receive a shoutout from the CEO at a company all-hands meeting or a private word of thanks from them?",
"Would you rather someone took a boring task off your to-do list or invited you to participate in a project of great interest to you?",
"What’s a time when someone did something you appreciated (at work or in another context), but you didn’t let them know? What held you back?",
"Would you rather talk like Yoda or breathe like Darth Vader?",
"Would you rather take a cold shower every day or always sleep an hour less than you need?",
"Which do you prefer, oceans or mountains? Why?",
"Would you rather speak all languages or be able to speak to animals?",
"Make a choice: Never hear music again or lose the ability to read?",
"What would you do if you came home and found a penguin in your freezer?",
"Do you have a non-work goal you're working towards right now? What is it?",
"You’ve been teleported to the middle ages. How do you make a living there?",
"What’s the last thing you completed that you’re proud of?",
"What’s something that made you smile recently?",
"What’s one of your favorite recent memories?",
"If you could have an animal sidekick, what animal would it be? Why?",
"What is one thing we would never guess about you?",
"What current fact about your life would most impress your five-year-old self?",
"What fruit or vegetable represents your mood today?",
"What's something you are craving right now?",
"What looks easy peasy lemon squeezy but is actually difficult difficult lemon difficult?",
"What’s something from your childhood that you still love today?",
"What healthy food tastes just as good to you as unhealthy food?",
"What’s a small act of kindness you were once shown that you’ll never forget?",
"What’s a movie you always recommend to people? Why do you love it?",
"What’s normal where you live, but might seem weird to the rest of the world?",
"You’ve died but instead of entering the afterlife, you've entered Earth 2.0. What are some things that make Earth 2.0 better?",
"What do you value most in a friendship?",
"What's something that you've never learned to do?",
"Where do you feel most at home?",
"What small thing would improve your day today?",
"If you could go back in time 10,000 years ago and make a cave painting to confuse everyone in the future, what would you draw?",
"What’s one characteristic you admire in others?",
"What’s an organization or private company you admire and why?",
"What was the first concert or gig you ever attended?",
"What ice cream flavour sums up your personality today?",
"What’s one thing your parents or guardians always nagged you about?",
"What’s something you do to relieve anger or stress?",
"When you were young what cartoon would you get up early to watch?",
"What’s a sauce, condiment or dressing you couldn’t live without?",
"Tell us about a stranger you still remember. What made them memorable?",
"What’s one thing you wish you’d been taught in school?",
"What’s an adult problem nobody prepared you for?",
"What’s something that doesn’t deserve the hate it gets?",
"What’s a simple life hack that everyone can benefit from?",
"What is a lesson you feel you learned too late in life?",
"What’s your spirit animal this week?",
"If buying groceries were a game, what would be one of the loading screen tips?",
"What's something you admire about the people on our team?",
"What's one of your pet peeves?",
"What’s an unusual skill you’d love to master?",
"If you had a magic button on your desk to bring you whatever you wanted, what would it summon?",
"What’s your guilty pleasure right now?",
"What was the last thing you did that gave you child-like joy?",
"What book would you like to live in?",
"What’s the last thing you did for the first time?",
"You've been chosen to represent your country in a global competition. What sport or activity are you doing?",
"If you could keep only one part of your morning routine, what would it be?",
"Do you work better with or without music? What are you listening to while you work?",
"Have you ever experienced a culture shock? Where was it and what happened?",
"If you had unlimited time and resources, how would you spend your days?",
"What was the first thing you thought about when you woke up today?",
"What’s something you would change if you ran the world?",
"If your home was packed full of golf balls how would you remove them?",
"If you did not have to sleep, how would you spend the extra 8 hours?",
"What thing from nature, excluding animals, best describes you today?",
"If you could do something that you don’t because it’s bad for you, but you could do it without repercussions – what would you do?",
"What question do you wish people would ask you?",
"If you could be one other person, who would that person be and why?",
"If you had to describe how you’re feeling right now as an amusement park ride, what ride are you on?",
"If you could safely eat any inedible object, what would it be?",
"What are you reading right now?",
"If you could pick up a new skill in an instant, what would it be?",
"Is there any topic lately that you would like to be mentored on?",
"When you’re feeling stressed, how do you deal with it?",
"How would you describe your communication style in 3 words?",
"Do you have any routines you use to improve your energy and focus?",
"What’s one new and interesting thing you’ve been thinking about lately?",
"If you had a remote control with only one button that controlled something in your life, what would the button do?",
"If money weren't a worry for you, how would you spend your days?",
"If you were to create a slogan for your life, what would the slogan be?",
"What sport would you compete in if you were in the Olympics?",
"What kind of day have you had so far today?",
"What's something from the past week that you would consider to be a 'win'?",
"What's the biggest challenge you want to overcome over the next few weeks?",
"What is your biggest learning or insight from this week",
"If you had to teach a class on one thing, what would you teach?",
"Where would you like to be if you weren't here, and why?",
"What’s your earliest memory?",
"What kind of car are you today?",
"What is one interest of yours that others in this group might not know about?",
"If you could only eat one food for the rest of your life, what would it be?",
"If you could change one thing about your work space, what would you do?",
"Name a song that you absolutely hate, but you're not sure why you hate it.",
"If you were a superhero today, which superhero would you be?",
"How do you recharge when you are low on energy?",
"What’s the most beautiful place near where you live?",
"What helps get you in the flow?",
"How do you deal with distraction?",
"What type of drink best describes your current mood?",
"If you could choose your age forever, what age would you choose and why?",
"What is a dream you have had recently?",
"You have to sing karaoke, what song do you pick?",
"What skills do you bring to your workplace that are currently underutilized?",
"Which emoji best describes your mood right now?",
"What color are you today, and why?",
"Fill in the blanks: I'm lost in the middle of the woods, and I'm feeling _____, so I think I will _________.",
"What are you grateful for?",
"If you were stranded on an island what item would you have with you?",
"What is a fashion trend you are really glad went away?",
"What’s one thing that brings you energy and joy?",
"What were you really into when you were a kid?",
"If there were a movie made about your life, what genre would it be and why?",
"What’s the best piece of advice you’ve ever been given?",
"Where is the most beautiful place you've ever been?",
"Are you spring, summer, fall, or winter? Please share why.",
"If you were a vegetable, what vegetable would you be?",
"Who should play you in the movie of your life?",
"Would you rather have the power of invisibility, or be able to fly -- and why?",
"If you were a weather report, what would your forecast be?",
"If you could go back in time to yesterday morning, what advice would you give yourself?",
"What's the best concert you've ever been to?",
"What type of transportation are you right now, and why?",
"If you could add any superpower to your abilities, what would you choose?",
"What is one fear would you like to conquer?",
"Of all your worldly possessions, what would be the hardest to give up?",
"In one word, describe how you are feeling right now.",
"Complete this sentence, I just won the lottery! If you're looking for me tomorrow, I'll be _____.",
"If you could live in a building of any type of architecture, what type would you choose, and why?",
"What was your first job?",
"If you were cereal, which cereal would you be and why?",
"If you had the chance to relive a day (any day in your life), what day would it be, and why?",
"If you were to have dinner with the main characters of the last show/movie you watched. Who would you have dinner with?",
"Please describe your morning routine with emojis",
"Tell us what would be your entrance theme song if you were a wrestler?",
"What’s a book/movie/show that you think everyone should watch/read? (Bonus points if you tell us why)",
"What’s a book, movie or show that everyone loves but you?",
"Post two emojis that describe passions or interests you have outside of Flatiron (bonus points if it is also something you haven't already shared with us!)",
"What was the last movie you watched? Did you like it?",
"What was your favorite cartoon when you were a kid?",
"What was the worst job you’ve ever had??",
"Which show you don’t regret having binged on and why?",
"Who is your least favorite band / musical artist and why? (if you have a reason) If you can’t think of one, the least favorite genre works!",
"60s, 70s, 80s, 90s, 00s: Which decade do you love the most and why?",
"If you could add anyone to Mount Rushmore who would it be?",
"What was your least favorite food as a child? Do you still hate it or do you love it now?",
"You have your own late night talk show, who do you invite as your first guest?",
"As a child, what did you want to be when you grew up?",
"What fictional world or place would you like to visit? Why?",
"If you could see one movie again for the first time, what would it be and why?",
"Share the most awesome website you know - or the website that totally changed your life!",
"Would you rather give up your smartphone or your computer? Why did you pick that?",
"You're going to sail around the world, what's the name of your boat?",
"What was a self-care/restful highlight of your weekend? ",
"Leave a comment with an emoji that describes how you are — you can be as abstract or as specific as you want. ",
"What advice would you give to someone who feels overwhelmed by the course and needs to find quick ways to relax throughout the day?",
"If you could turn the ocean into a liquid other than water, which one would you pick? (No animals would be harmed in the process)",
"What’s the best (or worst) knock-knock joke you know?",
"Post a few emojis that you haven't yet used before. I love discovering what emojis other people have added!",
"Is hotdog a sandwich? Is empanada a dumpling? Is cereal a soup? WHY???",
"Which commonly-available brand (and flavor) of ice-cream should I try and add to my top 10 list?",
"If you had to have animals instead of hands (proportional to your body, the whole animal), what would they be and why?",
"What historical or literary figure(s) would you take for a year-long trip to Mars?",
"What’s most confusing about what you’re learning right now?",
"What’s your favorite coding related meme/gif?",
"Share a gif that describes how you’re feeling about your work today.",
"What do you miss most about the previous Phase?",
"What is your favorite thing about this Phase so far?",
"If coding was an animal, what animal would it be and why?",
]
